name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonagem completa para melhor análise

      - name: Instalar MinGW e configurar GCC no Windows
        run: |
          choco install mingw -y
          echo "MinGW instalado. Verificando o caminho..."
          echo $env:Path
          $env:Path += ";C:\ProgramData\chocolatey\bin;C:\tools\mingw64\bin"
          echo "Novo caminho:"
          echo $env:Path

      - name: Compilar o projeto
        shell: bash
        run: |
          gcc Mercado.c -o Mercado.exe

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=tiagosdbastos_Projeto-mercado \
          -Dsonar.organization=tiagosdbastos \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
